### ISSUE TITLE
Need latest rpm for Rocky linux 9 OS

### ISSUE THREAD

**Issue by anburhce** [elico/squid-docker-build-nodes#2]
Hi  Eliezer Croitoru ,

I hope you are doing good.

Pls help us to create latest squid  rpm build for Rocky linux 9.

**Comment by elico** [comment]
@anburhce Hey, I have not updated this repo for a very long time and I do plan to do so but.. the issue is that squid since a specific version (at least 5.7) cannot be built on top of all EL9 distros including: RHEL, Rocky Alma, Oracle so for now the only thing is to wait for the squid-dev or rocky linux teams to resolve the relevant issues.
If you want to help with the issues please send an email to the squid-cache users mailing list.

**Comment by anburhce** [comment]
Hi Eliezer,

Thank you very much for your prompt support.

**Comment by elico** [comment]
@anburhce I have built squid 6.10 for Rocky linux and all other EL9 distributions and these are available on my public repo at:
https://www.ngtech.co.il/repo/

In order to build 6.10 on EL9 you need to disable LTO (link time optimization).
This issue existed on older versions of squid and EL distributions on the V4 branch using the next line in the rpm spec file
`%define _lto_cflags %{nil}`

This can be seen the SRPM file which are in the repo.

**Comment by elico** [comment]
The repo was updated
